/** Build settings
  */
ThisBuild / scalaVersion := "3.3.8"
ThisBuild / tpolecatDefaultOptionsMode := org.typelevel.sbt.tpolecat.DevMode

/** Maven Central publishing metadata
  */
ThisBuild / organization := "io.github.algebrazebra"
ThisBuild / organizationName := "Algebrazebra"
ThisBuild / organizationHomepage := Some(url("https://github.com/Algebrazebra"))
ThisBuild / homepage := Some(url("https://github.com/Algebrazebra/cronh"))
ThisBuild / scmInfo := Some(
  ScmInfo(
    url("https://github.com/Algebrazebra/cronh"),
    "scm:git:https://github.com/Algebrazebra/cronh.git"
  )
)
ThisBuild / versionScheme := Some("early-semver")
ThisBuild / developers := List(
  Developer(
    id = "algebrazebra",
    name = "Algebrazebra",
    email = "Algebrazebra@users.noreply.github.com",
    url = url("https://github.com/Algebrazebra")
  )
)
ThisBuild / description := "A Scala 3 library for defining human-readable cron schedules."
ThisBuild / licenses := List(License.Apache2)
ThisBuild / pomIncludeRepository := { _ => false }

/** GitHub Actions CI/CD workflow settings
  *
  * The workflows are automatically generated by the sbt-github-actions plugin.
  * The build configuration below is used to customize the generated workflow
  * steps.
  */

ThisBuild / githubWorkflowJavaVersions := Seq(JavaSpec.temurin("11"))

ThisBuild / githubWorkflowTargetTags ++= Seq("v*")

ThisBuild / githubWorkflowPublishTargetBranches :=
  Seq(RefPredicate.StartsWith(Ref.Tag("v")))

ThisBuild / githubWorkflowPublish := Seq(
  WorkflowStep.Sbt(
    commands = List("tpolecatReleaseMode", "ci-release"),
    name = Some("Publish to Maven Central"),
    env = Map(
      "PGP_PASSPHRASE" -> "${{ secrets.PGP_PASSPHRASE }}",
      "PGP_SECRET" -> "${{ secrets.PGP_SECRET }}",
      "SONATYPE_PASSWORD" -> "${{ secrets.SONATYPE_PASSWORD }}",
      "SONATYPE_USERNAME" -> "${{ secrets.SONATYPE_USERNAME }}"
    )
  )
)

ThisBuild / githubWorkflowBuild := Seq(
  WorkflowStep.Sbt(
    List("scalafmtSbtCheck", "scalafmtCheckAll"),
    name = Some("Check formatting")
  ),
  WorkflowStep.Sbt(
    List("tpolecatCiMode", "compile"),
    name = Some("Compile")
  ),
  WorkflowStep.Sbt(
    List("tpolecatCiMode", "test"),
    name = Some("Run tests")
  )
)

/** Custom `ci` task that runs all sbt commands defined in the GitHub Actions
  * workflow build steps. This keeps local CI execution in sync with the
  * generated workflow file.
  */
lazy val ci = taskKey[Unit]("Run all GitHub Actions build steps locally")

ci := {
  val log = streams.value.log
  val commands = (ThisBuild / githubWorkflowBuild).value.flatMap {
    case sbtStep: WorkflowStep.Sbt => sbtStep.commands
    case _                         => Nil
  }
  log.info(s"Running CI commands: ${commands.mkString(", ")}")
  val _ = commands.foldLeft(state.value) { (s, cmd) =>
    sbt.MainLoop.processCommand(sbt.Exec(cmd, None), s)
  }
}

/** Dependencies and versions
  */

lazy val mainDependencies: Seq[ModuleID] = Seq()

lazy val testDependencies: Seq[ModuleID] = Seq(
  "org.scalameta" %% "munit" % "1.3.5",
  "org.scalameta" %% "munit-scalacheck" % "1.3.0"
).map(_ % Test)

/** Project settings
  *
  * Here dependencies, settings, and tasks are wired up for the sbt projects.
  */

lazy val rootProject = (project in file("."))
  .settings(
    Seq(
      name := "cronh",
      libraryDependencies ++= mainDependencies ++ testDependencies
    )
  )
